[theme]
base="light"

[logger]
level="critical"

[runner]
fastReruns = true
enforceSerializableSessionState = false

[client]
showErrorDetails = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false